In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)

In [ ]:
import numpy as np
arr = np.array((1, 2, 3, 4, 5))
print(arr)

In [ ]:
import numpy as np

a = np.array(1)
b = np.array([1, 2, 3, 4, 5, 6])
c = np.array([[[1, 2, 3], [4, 5, 6]]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
3
3


In [ ]:
import numpy as np

a2 = np.array([1, 2, 3, 4], ndmin=2)
a3 = np.array([1, 2, 3, 4], ndmin=3)
a4 = np.array([1, 2, 3, 4], ndmin=4)

print(a2, a3, a4)
print('number of dimensions :', a2.ndim, a3.ndim, a4.ndim)

In [ ]:
import numpy as np

a2 = np.array([1, 2, 3, 4], ndmin=2)
a3 = np.array([1, 2, 3, 4], ndmin=3)
a4 = np.array([1, 2, 3, 4], ndmin=4)
print(a2[0,0])
print(a3[0,0,0])
print(a4[0,0,0,0])

print(a2, a3, a4)
print('number of dimensions :', a2.ndim, a3.ndim, a4.ndim)

1
1
1
[[1 2 3 4]] [[[1 2 3 4]]] [[[[1 2 3 4]]]]
number of dimensions : 2 3 4


In [ ]:
import numpy as np
a4 = np.array([1, 2, 3, 4], dmin=4)
print(a4)

In [ ]:
import matplotlib.image as img
import matplotlib.pyplot as plt

In [ ]:
img1 = img.imread("panda.jpg")
plt.imshow(img1)

In [ ]:
print(img1.ndim)
print(img1.shape)
plt.imshow(img1[:,:,0])

In [ ]:
print(img1.ndim)
print(img1.shape)
plt.imshow(img1[:,:,1])

In [ ]:
print(img1.ndim)
print(img1.shape)
plt.imshow(img1[:,:,2])

In [ ]:
print(img1[:,:,0])

In [ ]:
print(img1[:,:,1][0][1])

In [ ]:
a = np.array(range(1, 6))
print(a)
print(a.dtype)

In [ ]:
b = a.astype(float)
print(b.dtype)

In [ ]:
a1 = np.empty ([2, 2], dtype=int)
print(a1)#random values 
a2=np.zeros([2,2])
a3=np.ones([2,2])
print(a3-1)
a4=np.arange(1,10,2,int) #start, stop, step, dtype
print(a4)


[[4607182418800017408 4607182418800017408]
 [4607182418800017408 4607182418800017408]]
[[0. 0.]
 [0. 0.]]
[1 3 5 7 9]


###indexing 

In [ ]:
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[1, 1, 1], (arr[0, 1, 1]))

11 5


In [ ]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print(arr.shape)
print(arr[1, -1])
print(arr[1, :])

arr = arr[None, :, :]
print(arr.shape)
print(arr[0, 0, :])

(2, 5)
10
[ 6  7  8  9 10]
(1, 2, 5)
[1 2 3 4 5]


In [ ]:
import numpy as np
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
arr = arr[None, None,  :, :]
print(arr[:, 0, 1, 3], arr.ndim)

[9] 4


In [ ]:
import numpy as np

a = np.array([1, 2, 3, 4, 5, 6, 7])

print(a[4:])
print(a[:-1])
print(a[1:-1])
print(a[-1:-1])
print(a[0:0])

[5 6 7]
[1 2 3 4 5 6]
[2 3 4 5 6]
[]
[]


###PANDAS

In [ ]:
import pandas as pd
a = [1, 2, 3, 4]

s = pd.Series(a)
print(s)

In [ ]:
import pandas as pd
a = [1, 2, 3, 4]
s = pd.Series(a, index = ['a', 'b', 'c', 'd'])

print(s)

In [ ]:
import pandas as pd

a = {"Delhi": 'Bahadur shah zafer', "Allahbad": 'Liyakat Ali', 
            "Lucknow": 'Hazrat Mahal', "Kanpur":'NanaSaheb'}

s = pd.Series(a)

print(s)

In [ ]:
import pandas as pd
s = pd.Series(20, index = ['a', 'b', 'c', 'd'])

print(s)
print(s[2])

a    20
b    20
c    20
d    20
dtype: int64
20


##DATAFRAMES

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
c = np.array([[1, 2, 3], [4, 5, 6]])
df = pd.DataFrame(c)
print(df)

   0  1  2
0  1  2  3
1  4  5  6


In [ ]:
import pandas as pd
c = np.array([[1, 2, 3], [4, 5, 6]])
df = pd.DataFrame(c)
print(df.iloc[0,1])

2


In [ ]:
import pandas as pd
c = np.array([1, 2, 3])
print(c.size)
df = pd.DataFrame(c)
print(df.shape)
#print(df.iloc[0,2])

3
(3, 1)


In [ ]:
import pandas as pd

data = {
  "city": ['Francois Martin', 'Job Charnock', 'Baker & Edwin lutyens', 'Jane & Le Corbusier'],
  "Founder and Architect": ['pondicherry', 'Kolkata', 'Delhi', 'Chandigarh'],
  "year": [1673, 1690, 1927, 1950]
}

df = pd.DataFrame(data)

print(df)
df.to_csv('file1.csv')

                    city Founder and Architect  year
0        Francois Martin           pondicherry  1673
1           Job Charnock               Kolkata  1690
2  Baker & Edwin lutyens                 Delhi  1927
3    Jane & Le Corbusier            Chandigarh  1950


In [ ]:
df = pd.read_csv('file1.csv')

print(df) 

In [ ]:
#iloc is index based
df = pd.read_csv('file1.csv')

print(df) 
print()
#print(df.iloc[0,2])
#print()
#print(df.iloc[:,0])
#print()
print(df.iloc[:,'year'])
print()
print(df.iloc[:,:])
print()
print(df.iloc[:,0:2])

   Unnamed: 0                   city Founder and Architect  year
0           0        Francois Martin           pondicherry  1673
1           1           Job Charnock               Kolkata  1690
2           2  Baker & Edwin lutyens                 Delhi  1927
3           3    Jane & Le Corbusier            Chandigarh  1950



ValueError: ignored

In [ ]:
#loc is label based
df = pd.read_csv('file1.csv')
print(df)
print()
print(df.loc[0])
print()
print(df.loc[0, 'city'])
#print(df.loc[0, 1]) ERROR
print(df.iloc[0, 1]) #NO ERROR
print()
print(df.loc[(df.year == 1927)])
print()
print(df.loc[(df.year == 1927), 'city':'year'])



   Unnamed: 0                   city Founder and Architect  year
0           0        Francois Martin           pondicherry  1673
1           1           Job Charnock               Kolkata  1690
2           2  Baker & Edwin lutyens                 Delhi  1927
3           3    Jane & Le Corbusier            Chandigarh  1950

Unnamed: 0                             0
city                     Francois Martin
Founder and Architect        pondicherry
year                                1673
Name: 0, dtype: object

Francois Martin
Francois Martin

   Unnamed: 0                   city Founder and Architect  year
2           2  Baker & Edwin lutyens                 Delhi  1927

                    city Founder and Architect  year
2  Baker & Edwin lutyens                 Delhi  1927


In [ ]:
Belong_to = ['FEIC', 'BEIC', 'England', 'England']
df["Belong to"]  = Belong_to
print(df)
print()
print(df.iloc[:, 0])
df.to_csv('updated_file1.csv')


   Unnamed: 0                   city Founder and Architect  year Belong to
0           0        Francois Martin           pondicherry  1673      FEIC
1           1           Job Charnock               Kolkata  1690      BEIC
2           2  Baker & Edwin lutyens                 Delhi  1927   England
3           3    Jane & Le Corbusier            Chandigarh  1950   England

0    0
1    1
2    2
3    3
Name: Unnamed: 0, dtype: int64


In [ ]:
import pandas as pd

data = {
  "city": ['Francois Martin', 'Job Charnock', 'Baker & Edwin lutyens', 'Jane & Le Corbusier'],
  "Founder and Architect": ['pondicherry', 'Kolkata', 'Delhi', 'Chandigarh'],
  "year": [1673, 1690, 1927, 1950]
}

df3 = pd.DataFrame(data)

print(df3)
print('\n')
df3.to_csv('file2.csv', index = False)
print(df3.iloc[:,0])

                    city Founder and Architect  year
0        Francois Martin           pondicherry  1673
1           Job Charnock               Kolkata  1690
2  Baker & Edwin lutyens                 Delhi  1927
3    Jane & Le Corbusier            Chandigarh  1950


0          Francois Martin
1             Job Charnock
2    Baker & Edwin lutyens
3      Jane & Le Corbusier
Name: city, dtype: object
